### ISSUE TITLE
Create model WebProject with all most important Java technology and frameworks.

### ISSUE THREAD

**Issue by timyas** [timyas/java-muster#1]
The purpose of this model project is to show my ability and knowledges in Java,  SQL, Hibernate, Spring. As well like my capability to use and to apply tools like Maven, JUnit. 

As a result to proof my qualification for Java Junior position.

**Comment by peterarsentev** [comment]
Important, you need to create maven project. This project should build the WAR file, which can be deployed to Tomcat. I recommend you don't use Eclipse or maven web archetype for creating it. You should try to create all necessary structure by hands. You need to follow those steps https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html

**Comment by timyas** [comment]
Got it! I've made a clean Maven webapp project with 'war' packaging.

**Comment by peterarsentev** [comment]
I have checked. Evething is ok.
